In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [53]:
baseDPE = pd.read_csv("C:/Users/conta/Desktop/Python Dados Rio de Janeiro/BaseDPEvolucaoMensalCisp.csv", sep=';')
baseEstado_ano = pd.read_csv("C:/Users/conta/Desktop/Python Dados Rio de Janeiro/BaseEstadoTaxaAno.csv", sep=';')
baseEstado_mes = pd.read_csv("C:/Users/conta/Desktop/Python Dados Rio de Janeiro/BaseEstadoTaxaMes.csv", sep=';')
AISPpor_regiao = pd.read_csv("C:/Users/conta/Desktop/Python Dados Rio de Janeiro/AispPorRegiao.csv", sep=';')
#RelacaoRISP_AISP_CISP = pd.read_csv("C:/Users/conta/Desktop/Python Dados Rio de Janeiro/Relacao_RISPxAISPxCISP.csv", sep=';')

In [27]:
baseDPE.shape

(35670, 63)

In [51]:
baseDPE['ano'] = pd.to_datetime(baseDPE['ano'])
baseDPE['mes'] = pd.to_datetime(baseDPE['mes'])
baseEstado_ano['ano'] = pd.to_datetime(baseEstado_ano['ano'])
baseEstado_mes['mes'] = pd.to_datetime(baseEstado_mes['mes']).dt.month

In [50]:
baseEstado_mes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 57 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ano                         264 non-null    int64
 1   mes                         264 non-null    datetime64[ns]
 2   mes_ano                     264 non-null    object
 3   hom_doloso                  264 non-null    object
 4   lesao_corp_morte            264 non-null    object
 5   latrocinio                  264 non-null    object
 6   cvli                        264 non-null    object
 7   hom_por_interv_policial     264 non-null    object
 8   letalidade_violenta         264 non-null    object
 9   tentat_hom                  264 non-null    object
 10  lesao_corp_dolosa           264 non-null    object
 11  estupro                     264 non-null    object
 12  hom_culposo                 264 non-null    object
 13  lesao_corp_culposa          264 non-null    object
 14  roubo_transeunte            264 non-null    object
 15  roubo_celular               264 non-null    object
 16  roubo_em_coletivo           264 non-null    object
 17  roubo_rua                   264 non-null    object
 18  roubo_veiculo               263 non-null    object
 19  roubo_carga                 264 non-null    object
 20  roubo_comercio              264 non-null    object
 21  roubo_residencia            264 non-null    object
 22  roubo_banco                 264 non-null    object
 23  roubo_cx_eletronico         264 non-null    object
 24  roubo_conducao_saque        264 non-null    object
 25  roubo_apos_saque            264 non-null    object
 26  roubo_bicicleta             132 non-null    object
 27  outros_roubos               264 non-null    object
 28  total_roubos                264 non-null    object
 29  furto_veiculos              264 non-null    object
 30  furto_transeunte            264 non-null    object
 31  furto_coletivo              264 non-null    object
 32  furto_celular               264 non-null    object
 33  furto_bicicleta             132 non-null    object
 34  outros_furtos               264 non-null    object
 35  total_furtos                264 non-null    object
 36  sequestro                   264 non-null    object
 37  extorsao                    264 non-null    object
 38  sequestro_relampago         264 non-null    object
 39  estelionato                 264 non-null    object
 40  apreensao_drogas            264 non-null    object
 41  posse_drogas                228 non-null    object
 42  trafico_drogas              228 non-null    object
 43  apreensao_drogas_sem_autor  228 non-null    object
 44  recuperacao_veiculos        263 non-null    object
 45  apf                         228 non-null    object
 46  aaapai                      228 non-null    object
 47  cmp                         228 non-null    object
 48  cmba                        228 non-null    object
 49  ameaca                      264 non-null    object
 50  pessoas_desaparecidas       264 non-null    object
 51  encontro_cadaver            264 non-null    object
 52  encontro_ossada             264 non-null    object
 53  pol_militares_mortos_serv   132 non-null    object
 54  pol_civis_mortos_serv       132 non-null    object
 55  registro_ocorrencias        264 non-null    object
 56  fase                        264 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(54)
memory usage: 117.7+ KB

In [32]:
(baseEstado_ano['ano']).info()

<class 'pandas.core.series.Series'>
RangeIndex: 21 entries, 0 to 20
Series name: ano
Non-Null Count  Dtype
--------------  -----
21 non-null     datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 300.0 bytes

In [55]:
colunas_para_apagar = ['ano', 'mes_ano', 'fase']
baseEstado_mes = baseEstado_mes.drop(columns=colunas_para_apagar)

In [58]:
baseEstado_mes.head()

,mes,hom_doloso,lesao_corp_morte,latrocinio,cvli,hom_por_interv_policial,letalidade_violenta,tentat_hom,lesao_corp_dolosa,estupro,...,aaapai,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias
0,1,"4,01","0,04","0,14","4,19","0,61","4,8","2,48","46,94","1,67",...,NaN,NaN,NaN,"41,71","2,78","0,98","0,02",NaN,NaN,"304,9"
1,2,"3,97","0,03","0,08","4,08","0,76","4,83","2,46","48,32","1,5",...,NaN,NaN,NaN,"41,16","2,89","1,27","0,03",NaN,NaN,"309,05"
2,3,"4,17","0,03","0,11","4,32","0,77","5,08","2,26","47,43","1,61",...,NaN,NaN,NaN,"39,43","3,14","1,06","0,05",NaN,NaN,"309,13"
3,4,"3,98","0,07","0,1","4,15","0,85",5,"2,02","43,84","1,46",...,NaN,NaN,NaN,"38,29","2,35","0,82","0,03",NaN,NaN,"300,72"
4,5,"4,08","0,04","0,14","4,25","0,65","4,91","2,59","39,77","1,29",...,NaN,NaN,NaN,37,"2,84",1,"0,03",NaN,NaN,"310,15"

In [ ]:

df_unido = pd.merge(baseDPE, baseEstado_mes, left_on='mes', right_on='mes', how='inner')
df_unido = pd.merge(df_unido, baseEstado_ano, left_on='ano', right_on='ano', how='inner')

df_unido.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso_x,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase_y
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,"467,97","32,33","10,95","0,36",NaN,NaN,"3611,67",3
1,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,"467,97","32,33","10,95","0,36",NaN,NaN,"3611,67",3
2,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,"467,97","32,33","10,95","0,36",NaN,NaN,"3611,67",3
3,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,"467,97","32,33","10,95","0,36",NaN,NaN,"3611,67",3
4,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,"467,97","32,33","10,95","0,36",NaN,NaN,"3611,67",3

In [ ]:
dados_ausentes = df_unido.isnull().sum()

print(dados_ausentes)

cisp                     0
mes                      0
ano                      0
mes_ano                  0
aisp                     0
                        ..
pessoas_desaparecidas    0
encontro_cadaver         0
encontro_ossada          0
registro_ocorrencias     0
fase_y                   0
Length: 168, dtype: int64

In [61]:
colunas_para_apagar = ['pol_militares_mortos_serv', 'pol_civis_mortos_serv' ]
df_unido = df_unido.drop(columns=colunas_para_apagar)

In [ ]:
plt.Figure(figsize=(10, 6))
plt.barh(df_unido['ano'],  df_unido[''])

In [63]:
df_unido.head()

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso_x,...,apf,aaapai,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,registro_ocorrencias,fase_y
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,NaN,NaN,"467,97","32,33","10,95","0,36","3611,67",3
1,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,NaN,NaN,"467,97","32,33","10,95","0,36","3611,67",3
2,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,NaN,NaN,"467,97","32,33","10,95","0,36","3611,67",3
3,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,NaN,NaN,"467,97","32,33","10,95","0,36","3611,67",3
4,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,NaN,NaN,"467,97","32,33","10,95","0,36","3611,67",3